### PR TITLE
BE: Session [] variables are to be used across the application

### PR DESCRIPTION
**Pull request by chris-gao-36**

### CODE REVIEW

**Comment by chris-gao-36** [comment]
This task aims to pass the username to every page, and added session checks to pages other than the login and register pages to ensure the username can be correctly displayed.

**Comment by SDzartov** [comment]
rebase from develop and then check for conflicts on app/py

**Comment by chris-gao-36** [comment]
Due to a lengthy delay in code review, significant code conflicts have arisen. I will close this branch and implement the functionality to pass the username to every page and add session checks to all pages except login and register on another branch, ensuring that the username can be properly displayed.

**Comment by chris-gao-36** [comment]
https://github.com/DataBytes-Organisation/Neo_Dolfin/pull/131
I have revised and pull request again for the new branch. Because the place that should belong to me to write the module was changed by others in advance, I need to fetch others to redo it

This branch achieved two main functionalities:

1. Passing the username to every page and adding session checks to all pages except the login and register pages, ensuring the username is correctly displayed.
2. Implemented the logout feature, which clears session data to prevent caching, and ensures secure pages are properly intercepted after logging out.

**Review by SDzartov — APPROVED** [review]

**Pull request merged**
