### PR TITLE
Registration Page Implementation

### PR DESCRIPTION
**Pull request by Vishalk4kumar**
Committing

### CODE REVIEW

**Review by hmm007 — CHANGES_REQUESTED** [review]
There has been no outline of what the changes you're introducing should be doing. On that end, I've seen you've reformatted and redesigned the Registration page, creating some new fields such as: 

- First name 
- last name
- birth 
- number 
- password 
- confirm password 
- occupation 
- address
- postal code 
- country 

I note that in your creation of an entirely new form, you've removed the current checkfield feature used to validate passwords against their requirements with regard to complexity (i.e. requiring a mix of uppercase, lowercase, numbers and symbols), and to ensure that no "common" password is in use. 

Note that the checkfield only appears upon interaction with that input field (lines 72 - 79, html and corresponding .css) If you wanted to redesign the look of the checkfield, that would be fine, however its complete removal is something that isn't in Dolfin's security's best interests. I.e. removal of this function means that passwords used for accounts are weak, and hence open to brute-force attacks.

**Comment by Vishalk4kumar** [comment]
Thank you for bringing this to my attention. I appreciate your thorough review of the registration page redesign.

Regarding the password validation feature, I understand the importance of maintaining strong security measures to protect our users' accounts. I apologize for the oversight in removing the password complexity checkfield without implementing an alternative validation method.

To address this, I will ensure that the redesigned registration page includes robust password validation functionality. This will include checking for the following criteria:

Minimum length requirement
Mix of uppercase and lowercase letters
Inclusion of numbers
Inclusion of special characters
Additionally, I will incorporate a check to ensure that common passwords are not used, thereby further enhancing the security of user accounts.

Thank you for highlighting this concern, and I will prioritize the implementation of password validation to strengthen Dolfin's security measures. If you have any further suggestions or requirements regarding this feature, please feel free to let me know.

**Comment by hmm007** [comment]
> Thank you for bringing this to my attention. I appreciate your thorough review of the registration page redesign.
> 
> Regarding the password validation feature, I understand the importance of maintaining strong security measures to protect our users' accounts. I apologize for the oversight in removing the password complexity checkfield without implementing an alternative validation method.
> 
> To address this, I will ensure that the redesigned registration page includes robust password validation functionality. This will include checking for the following criteria:
> 
> Minimum length requirement Mix of uppercase and lowercase letters Inclusion of numbers Inclusion of special characters Additionally, I will incorporate a check to ensure that common passwords are not used, thereby further enhancing the security of user accounts.
> 
> Thank you for highlighting this concern, and I will prioritize the implementation of password validation to strengthen Dolfin's security measures. If you have any further suggestions or requirements regarding this feature, please feel free to let me know.

No I don't think you understand, the password complexity features are already included with the current design. Just, merge it into your redesign instead of removing it in its entirety.

**Comment by Vishalk4kumar** [comment]
I will do that

**Comment by Vishalk4kumar** [comment]
I have updated the requested changes. Kindly review this and let me know if there are any further changes. Thank you

**Review by hmm007 — APPROVED** [review]
Hey, so I've reviewed the changes you made in the codespace. The visual is nice, on the whole, however, the checkfield is no longer interactive. So even though you've un-deleted the css and html that was involved, all that is showing up is the red text that doesn't turn green anymore, and somehow the entirety of the internal denial list function has been removed. I.e.  Password complexity check code exists, but is no longer interactive, hasn't been properly merged.

I'm approving this commit, but I'll be fixing this issue myself because you've made several commits to change your code in-line with the requests I made but have been unable to resolve the issue adequately.

https://github.com/DataBytes-Organisation/Neo_Dolfin/assets/112069519/c81399d1-f7a0-422b-8e22-7ba87ab2b5d7

**Comment by Vishalk4kumar** [comment]
Thank you for reviewing the changes! I appreciate your feedback. It seems like there's still an issue with the functionality of the checkfield feature. I understand that despite my efforts, it's not working as expected. Would you like me to take another shot at fixing it? It's possible that the problem lies within the JavaScript file, which I haven't worked on yet. Let me know how you'd like to proceed!"

Also, May I know your name please so I can contact you on teams?

**Comment by hmm007** [comment]
> Thank you for reviewing the changes! I appreciate your feedback. It seems like there's still an issue with the functionality of the checkfield feature. I understand that despite my efforts, it's not working as expected. Would you like me to take another shot at fixing it? It's possible that the problem lies within the JavaScript file, which I haven't worked on yet. Let me know how you'd like to proceed!"
> 
> Also, May I know your name please so I can contact you on teams?

Hey, so it's Heera. And no, it's fine, I'll just fix it myself. 

It's an issue with the javascript not reading the newly named input variables, and I don't think it's collected the separate strings (reflecting different requirements) properly. I'll be able to fix it myself, don't worry about it.

**Pull request merged**
