### PR TITLE
home page

### PR DESCRIPTION
**Pull request by souha1418**
please review the home page

### CODE REVIEW

**Comment by SDzartov** [comment]
image
You need to copy the nav bar from the develop home page. 
You need to centerise and scale your html images.

**Review by RyanBowenDeakin — APPROVED** [review]

**Review by SDzartov — CHANGES_REQUESTED** [review]
Home page needs to be updated to reflect design choices. Review on Sunday meeting.

**Comment by SDzartov** [comment]
@BlakeLatch Please have a look.

**Comment by SDzartov** [comment]
Discussed with @BlakeLatch , merging based on agreement for revision.

**Pull request merged**
